name: Build and Upload .NET GUI App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build-dotnet:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore GUI/InterceptSuite/InterceptSuite.csproj

    - name: Build
      run: dotnet build GUI/InterceptSuite/InterceptSuite.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish GUI/InterceptSuite/InterceptSuite.csproj --configuration Release --no-build --output publish

    - name: Package Application
      run: |
        # Create a ZIP package of the published files
        $versionInfo = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("${{ github.workspace }}\publish\InterceptSuite.exe")
        $version = "$($versionInfo.FileMajorPart).$($versionInfo.FileMinorPart).$($versionInfo.FileBuildPart)"

        # In case version info can't be read, use a default version
        if (-not $version -or $version -eq "..") {
          $version = "1.0.0"
        }

        echo "App version: $version"

        # Create output directory
        New-Item -Path "package" -ItemType Directory -Force

        # Create the ZIP file
        Compress-Archive -Path "publish\*" -DestinationPath "package\InterceptSuite-GUI-v$version-win-x64.zip"

        echo "✅ Package created successfully: InterceptSuite-GUI-v$version-win-x64.zip"

    - name: Upload GUI Package
      uses: actions/upload-artifact@v4
      with:
        name: InterceptSuite-GUI
        path: package/InterceptSuite-GUI-*.zip
        if-no-files-found: error
        retention-days: 90
