name: Build Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: windows-latest
    env:
      CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    steps:
    - uses: actions/checkout@v4

    - name: Get vcpkg
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg
        path: vcpkg

    - name: Configure CMake
      run: cmake -B build-release -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build-release --config Release

    - name: Package
      working-directory: build-release
      run: cpack -G ZIP -C Release

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: TLS-MITM-Proxy-Windows
        path: build-release/TLS-MITM-Proxy-*.zip
        if-no-files-found: error
        retention-days: 90
