name: Build Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup vcpkg
      shell: pwsh
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe integrate install
        .\vcpkg\vcpkg.exe install openssl:x64-windows
        
    - name: Configure CMake
      shell: pwsh
      run: |
        cmake -B build-release -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      shell: pwsh
      run: |
        cmake --build build-release --config Release

    - name: Package
      shell: pwsh
      run: |
        cd build-release
        cpack -G ZIP -C Release

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: TLS-MITM-Proxy-Windows
        path: build-release/TLS-MITM-Proxy-*.zip
        if-no-files-found: error
        retention-days: 90
